# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sleep-1:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-2:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-3:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-4:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-5:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-6:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-7:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-8:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-9:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-10:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-11:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  sleep-12:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Sleep for 1 min
        run: |
          echo echo Wait for 1 min!!
          sleep 60
          echo test, and deploy your project.
  docker-build:
    # The type of runner that the job will run on
    runs-on:
      - demo
      - eks

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Docker build to test if DinD is working properly
        run: |
          echo Perform docker build,
          pwd
          cd .github/workflows
          pwd
          docker image build -t from-standalone-runner .
          docker image ls -a
