apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster
  region: ap-south-1
  version: "1.21"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: keypair
    volumeSize: 30
