apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster
  region: ap-south-1
  version: "1.21"

vpc:
  id: "vpc-abcd12346"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.1.0/24"       # (optional, must match CIDR used by the given VPC)
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      ap-south-1a:
        id: "subnet-abcd1234hhb"
        cidr: "192.168.1.0/26" # (optional, must match CIDR used by the given subnet)

      ap-south-1b:
        id: "subnet-xyz11hh445"
        cidr: "192.168.1.64/26"  # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: keypair
    volumeSize: 30
    privateNetworking: true
    subnets:
      - subnet-aaahhbbddh3456
      - subnet-sfsdf3543457ff
